### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ebportal** [ScruffyFurn/AzureMultiplayerPOC#1]
I use VS2013 Premium.
it all compiles but nothing actually happens.

**Comment by ScruffyFurn** [comment]
Hi ebportal, can you explain a little more. Are there errors at runtime? What browser are you using to view the game?

**Comment by ebportal** [comment]
I get a blank empty page.

IE & FF

**Comment by ScruffyFurn** [comment]
What is the output/errors in the developer tools console (F12 in IE) ?

**Comment by ebportal** [comment]
None. see for yourself http://azurempg.azurewebsites.net

**Comment by ebportal** [comment]
Just found this error using FF Dev Tools:
ReferenceError: io is not defined in Game.js Line 51.
this is the line
var socket = io.connect('http://azurempgpoc.azurewebsites.net:80');

**Comment by ebportal** [comment]
Even this one doesn't work. http://azuregamepoc.azurewebsites.net/

**Comment by ScruffyFurn** [comment]
Fixes have been made to address connection issues. Check the spelling though, http://azurerpgpoc.azurewebsites.net:80
